--- #发布应用配置
upload_picname: 'publish/11.PNG'
upload_sql: 'publish/db-schema.sql'
upload_filename: 'spring_mysql.zip'
username_publish: '44@44.com'
password_publish: '123456'
app_name: '00x'
show_name: '00x'

scroll_bottom: >
  $('html, body').animate({ scrollTop: $(document).height()-$(window).height() });
# 滚动到页面顶部js
scroll_top: >
  $('html, body').animate({ scrollTop: 0 }, 'slow');

# 选择文件上传类型时候的jquery实现
vclick_even: |
  setTimeout(function(){
    $('.bootstrapchosen').trigger('liszt:open');
    setTimeout(function(){
      $('#arrangeway').val(%1$s).trigger('change');
      $('#arrangeway_chzn_o_1').trigger('click');
      $('.bootstrapchosen').trigger('liszt:updated');
      $('footer').trigger('click');
    },500)
  },1)
# 文件上传类型：0表示本地文件，1表示远程文件
filetype: 0
# 设置file的可见性，使其对于selenium可见
file_visiable: >
  $('#%s').eq(0).attr('style','height:20px;opacity:1;display:block;
  position:static;transform:translate(0px, 0px) scale(1)')
# 访问应用的button点击的jquery实现
window_open: >
  u = $('#visitBtn').attr('onclick');
  $('#visitBtn').attr('onclick', $('#visitBtn').attr('onclick').substring(
  0, u.length - 1) + ", 'visitWindow')")
